apiVersion: v1
kind: Service
metadata:
  name: boltchats-api
  namespace: boltchats
  labels:
    app: boltchats-api
spec:
  type: ClusterIP
  selector:
    app: boltchats-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
