apiVersion: v1
kind: Service
metadata:
  name: boltchats-web
  namespace: boltchats
  labels:
    app: boltchats-web
spec:
  type: ClusterIP
  selector:
    app: boltchats-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
