apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boltchats

bases:
  - ../../base
  - ../../components

resources:
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml

images:
  - name: ghcr.io/developer-emre/boltchats-api
    newTag: latest
  - name: ghcr.io/developer-emre/boltchats-ws
    newTag: latest
  - name: ghcr.io/developer-emre/boltchats-storage
    newTag: latest
  - name: ghcr.io/developer-emre/boltchats-web
    newTag: latest

configMapGenerator:
  - name: boltchats-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
