apiVersion: apps/v1
kind: Deployment
metadata:
  name: boltchats-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boltchats-ws
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boltchats-storage
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boltchats-web
spec:
  replicas: 1
