"""Request/Response schemas for all API endpoints"""

from .auth import (
    CurrentUserResponse,
    HealthResponse,
    LoginRequest,
    RefreshTokenRequest,
    RegisterRequest,
    TokenResponse,
)
from .conversation import (
    ConversationCreateRequest,
    ConversationListResponse,
    ConversationResponse,
    ConversationUpdateRequest,
    CustomerCreateRequest,
    CustomerIdentityResponse,
    CustomerResponse,
    DraftResponse,
    LabelCreateRequest,
    LabelResponse,
    LabelUpdateRequest,
    MessageCreateRequest,
    MessageDeleteRequest,
    MessageListResponse,
    MessageResponse,
    MessageUpdateRequest,
)
from .integration import (
    EventResponse,
    IntegrationCreateRequest,
    IntegrationResponse,
    IntegrationUpdateRequest,
    NotificationCreateRequest,
    NotificationListResponse,
    NotificationResponse,
    WebhookResponse,
    WorkflowStatusResponse,
)
from .organization import (
    InvitationAcceptRequest,
    InvitationCreateRequest,
    InvitationResponse,
    MemberCreateRequest,
    MemberListResponse,
    MemberResponse,
    MemberRoleResponse,
    MemberUpdateRequest,
    OrganizationCreateRequest,
    OrganizationResponse,
    OrganizationUpdateRequest,
    PermissionResponse,
    RoleCreateRequest,
    RoleResponse,
    RoleUpdateRequest,
    TeamCreateRequest,
    TeamResponse,
    TeamUpdateRequest,
    WorkspaceCreateRequest,
    WorkspaceResponse,
    WorkspaceUpdateRequest,
)

__all__ = [
    # Auth
    "RegisterRequest",
    "LoginRequest",
    "RefreshTokenRequest",
    "TokenResponse",
    "CurrentUserResponse",
    "HealthResponse",
    # Conversation
    "CustomerCreateRequest",
    "CustomerResponse",
    "CustomerIdentityResponse",
    "ConversationCreateRequest",
    "ConversationUpdateRequest",
    "ConversationResponse",
    "ConversationListResponse",
    "MessageCreateRequest",
    "MessageUpdateRequest",
    "MessageDeleteRequest",
    "MessageResponse",
    "MessageListResponse",
    "LabelCreateRequest",
    "LabelUpdateRequest",
    "LabelResponse",
    "DraftResponse",
    # Organization
    "OrganizationCreateRequest",
    "OrganizationUpdateRequest",
    "OrganizationResponse",
    "WorkspaceCreateRequest",
    "WorkspaceUpdateRequest",
    "WorkspaceResponse",
    "MemberCreateRequest",
    "MemberUpdateRequest",
    "MemberResponse",
    "MemberRoleResponse",
    "MemberListResponse",
    "TeamCreateRequest",
    "TeamUpdateRequest",
    "TeamResponse",
    "PermissionResponse",
    "RoleCreateRequest",
    "RoleUpdateRequest",
    "RoleResponse",
    "InvitationCreateRequest",
    "InvitationAcceptRequest",
    "InvitationResponse",
    # Integration & Notification
    "IntegrationCreateRequest",
    "IntegrationUpdateRequest",
    "IntegrationResponse",
    "WebhookResponse",
    "NotificationCreateRequest",
    "NotificationResponse",
    "NotificationListResponse",
    "EventResponse",
    "WorkflowStatusResponse",
]
